"""Benchmark metric definitions + recalculable per-request ledger (Week-2 P0-④/⑤).

Public surface consumed by bench_runner, reports, MLflow, and item ⑤:
  - RequestRecord / RequestLedger / RunConditions
  - TerminationReason / RequestOutcome
  - AggregateMetrics / LatencyStat
  - compute_tpot_ms, recalculate_from_ledger, ledger_to_experiment_fields
  - persist_ledger / load_ledger
  - interleave_schedule / verdict_from_ledgers / is_confirmed_promotable
"""

from inferops.metrics.aggregate import (
    AggregateMetrics,
    LatencyStat,
    apply_aggregate_to_result_fields,
    format_aggregate_report,
    ledger_to_experiment_fields,
    recalculate_from_ledger,
)
from inferops.metrics.confirm import (
    CONFIRMABLE_METRICS,
    DEFAULT_MIN_PAIRS,
    DEFAULT_MIN_REL_DELTA,
    ConfirmationDecision,
    ConfirmationVerdict,
    NumericSignal,
    PairClass,
    RepeatArm,
    RepeatCampaign,
    RepeatPhase,
    RepeatSlot,
    conditions_fingerprint,
    conditions_match,
    evaluate_campaign,
    format_confirmation_report,
    interleave_schedule,
    is_confirmed_promotable,
    primary_metric_value,
    relative_delta,
    require_same_conditions,
    run_interleaved_repeats,
    verdict_from_ledgers,
)
from inferops.metrics.definitions import (
    ERROR_OUTCOMES,
    LATENCY_SUCCESS_OUTCOMES,
    TPOT_MIN_OUTPUT_TOKENS,
    TTFT_SAMPLE_SCOPE,
    TPOT_SAMPLE_SCOPE,
    E2E_SAMPLE_SCOPE,
    compute_tpot_ms,
    is_error_for_rate,
    is_latency_eligible,
    is_tpot_eligible,
    is_ttft_eligible,
    percentile,
)
from inferops.metrics.ledger import (
    LEDGER_SCHEMA_VERSION,
    RequestLedger,
    RequestOutcome,
    RequestRecord,
    RunConditions,
    TokenCountSource,
    TerminationReason,
    load_ledger,
    persist_ledger,
)
from inferops.metrics.report import (
    ledger_from_result,
    report_from_ledger,
    report_from_result,
)

__all__ = [
    "CONFIRMABLE_METRICS",
    "DEFAULT_MIN_PAIRS",
    "DEFAULT_MIN_REL_DELTA",
    "ERROR_OUTCOMES",
    "LATENCY_SUCCESS_OUTCOMES",
    "TPOT_MIN_OUTPUT_TOKENS",
    "TTFT_SAMPLE_SCOPE",
    "TPOT_SAMPLE_SCOPE",
    "E2E_SAMPLE_SCOPE",
    "AggregateMetrics",
    "ConfirmationDecision",
    "ConfirmationVerdict",
    "LatencyStat",
    "LEDGER_SCHEMA_VERSION",
    "NumericSignal",
    "PairClass",
    "RepeatArm",
    "RepeatCampaign",
    "RepeatPhase",
    "RepeatSlot",
    "RequestLedger",
    "RequestOutcome",
    "RequestRecord",
    "RunConditions",
    "TokenCountSource",
    "TerminationReason",
    "apply_aggregate_to_result_fields",
    "compute_tpot_ms",
    "conditions_fingerprint",
    "conditions_match",
    "evaluate_campaign",
    "format_aggregate_report",
    "format_confirmation_report",
    "interleave_schedule",
    "is_confirmed_promotable",
    "is_error_for_rate",
    "is_latency_eligible",
    "is_tpot_eligible",
    "is_ttft_eligible",
    "ledger_from_result",
    "ledger_to_experiment_fields",
    "load_ledger",
    "percentile",
    "persist_ledger",
    "primary_metric_value",
    "recalculate_from_ledger",
    "relative_delta",
    "report_from_ledger",
    "report_from_result",
    "require_same_conditions",
    "run_interleaved_repeats",
    "verdict_from_ledgers",
]
